# Generated by Django 4.2 on 2026-03-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='tipo_poliza',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('HOGAR', 'Hogar'), ('VIDA', 'Vida'), ('COMERCIO', 'Comercio'), ('AP', 'Accidentes Personales'), ('RC', 'Responsabilidad Civil'), ('OTRO', 'Otro')], default='AUTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='policy',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
