# Generated by Django 4.2 on 2026-03-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policy_tipo_poliza_alter_policy_insurance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='pdf_poliza',
            field=models.FileField(blank=True, null=True, upload_to='polizas/'),
        ),
    ]
