# Generated by Django 4.2 on 2026-03-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_pdf_poliza'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='cuponera_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cuponeras/'),
        ),
        migrations.AddField(
            model_name='policy',
            name='forma_pago',
            field=models.CharField(choices=[('TARJETA', 'Tarjeta de crédito'), ('CBU', 'Débito / CBU'), ('CUPONERA', 'Cuponera de pago')], default='TARJETA', max_length=20),
        ),
    ]
