# Generated by Django 4.2 on 2026-03-12 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_dni_alter_client_first_name_and_more'),
        ('policies', '0004_policy_cuponera_pdf_policy_forma_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['end_date'], 'verbose_name': 'Póliza', 'verbose_name_plural': 'Pólizas'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='company',
            field=models.CharField(max_length=100, verbose_name='Compañía'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cuponera_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cuponeras/', verbose_name='Cuponera PDF'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='forma_pago',
            field=models.CharField(choices=[('TARJETA', 'Tarjeta de crédito'), ('CBU', 'Débito / CBU'), ('CUPONERA', 'Cuponera de pago')], default='TARJETA', max_length=20, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='insurance_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Detalle del seguro'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='pdf_poliza',
            field=models.FileField(blank=True, null=True, upload_to='polizas/', verbose_name='PDF de póliza'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(max_length=50, verbose_name='Número de póliza'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='tipo_poliza',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('HOGAR', 'Hogar'), ('VIDA', 'Vida'), ('COMERCIO', 'Comercio'), ('AP', 'Accidentes Personales'), ('RC', 'Responsabilidad Civil'), ('OTRO', 'Otro')], default='AUTO', max_length=20, verbose_name='Tipo de póliza'),
        ),
    ]
