# Generated by Django 4.2.16 on 2026-03-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_alter_policy_options_alter_policy_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='frecuencia_cuponera',
            field=models.IntegerField(blank=True, choices=[(1, 'Mensual'), (3, 'Trimestral'), (4, 'Cuatrimestral'), (6, 'Semestral')], help_text='Solo si la forma de pago es cuponera', null=True, verbose_name='Frecuencia de cuponera (meses)'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Número de póliza'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['end_date'], name='policies_po_end_dat_649bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_number'], name='policies_po_policy__a03f9f_idx'),
        ),
    ]
