# Generated by Django 4.2.16 on 2026-03-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_alter_policy_frecuencia_cuponera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='frecuencia_cuponera',
            field=models.IntegerField(blank=True, choices=[(1, 'Mensual'), (3, 'Trimestral'), (4, 'Cuatrimestral'), (6, 'Semestral'), (12, 'Anual')], null=True, verbose_name='Frecuencia de cuponera (meses)'),
        ),
    ]
