# Generated by Django 4.2.16 on 2026-03-15 06:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_alter_policy_frecuencia_cuponera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='cuponera_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Cuponera PDF'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='pdf_poliza',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='PDF de póliza'),
        ),
    ]
