# Generated by Django 4.2.16 on 2026-03-17 21:28

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_company_policy_company_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(verbose_name='Número de cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
                ('comprobante', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Comprobante')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='policies.policy', verbose_name='Póliza')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
