# Generated by Django 4.2.16 on 2026-03-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0011_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comprobante',
            field=models.TextField(blank=True, null=True, verbose_name='URL comprobante'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cuponera_pdf',
            field=models.TextField(blank=True, null=True, verbose_name='URL cuponera'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='pdf_poliza',
            field=models.TextField(blank=True, null=True, verbose_name='URL PDF de póliza'),
        ),
    ]
