# Generated by Django 4.2.16 on 2026-03-21 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0012_alter_payment_comprobante_alter_policy_cuponera_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='email_vencimiento_enviado',
            field=models.BooleanField(default=False, verbose_name='Email de vencimiento enviado'),
        ),
    ]
