# Generated by Django 4.2.16 on 2026-03-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0013_policy_email_vencimiento_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False, verbose_name='Recordatorio enviado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROXIMO', 'Próximo a vencer'), ('HOY', 'Vence hoy'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
    ]
