# Generated by Django 4.2.16 on 2026-03-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0014_payment_recordatorio_enviado_alter_payment_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compañía'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='company_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.company', verbose_name='Compañía'),
        ),
    ]
