# Generated by Django 4.2.16 on 2026-04-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_fecha_nacimiento_and_more'),
        ('policies', '0017_force_company_obj_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENCIMIENTO_POLIZA', 'Vencimiento de póliza'), ('VENCIMIENTO_CUPONERA', 'Vencimiento de cuponera'), ('CUMPLEANOS', 'Cumpleaños')], max_length=50)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ERROR', 'Error'), ('OMITIDO', 'Omitido')], max_length=20)),
                ('destinatario', models.EmailField(blank=True, max_length=254, null=True)),
                ('asunto', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='clients.client')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='policies.payment')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='policies.policy')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
