# Generated by Django 4.2.16 on 2026-05-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0018_emaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='fecha_primer_vencimiento_cuponera',
            field=models.DateField(blank=True, help_text='Si se deja vacío, se usará la fecha de inicio de la póliza.', null=True, verbose_name='Fecha primer vencimiento cuponera'),
        ),
    ]
