# Generated by Django 4.2.16 on 2026-05-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0019_policy_fecha_primer_vencimiento_cuponera'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emaillog',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'Registro de Email', 'verbose_name_plural': 'Registros de Emails'},
        ),
        migrations.AddField(
            model_name='policy',
            name='ultimo_envio_cuponera',
            field=models.DateField(blank=True, null=True, verbose_name='Última Cuponera Enviada'),
        ),
        migrations.AddField(
            model_name='policy',
            name='ultimo_envio_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Último Aviso Vencimiento'),
        ),
    ]
