# Generated by Django 4.2.16 on 2026-05-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0020_alter_emaillog_options_policy_ultimo_envio_cuponera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Riesgo',
                'verbose_name_plural': 'Tipos de Riesgos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='policy',
            name='tipo_poliza',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('MOTO', 'Moto'), ('HOGAR', 'Hogar'), ('VIDA', 'Vida'), ('COMERCIO', 'Comercio'), ('AP', 'Accidentes Personales'), ('RC', 'Responsabilidad Civil'), ('OTRO', 'Otro')], default='AUTO', max_length=20, verbose_name='Tipo de póliza (Categoría)'),
        ),
        migrations.AddField(
            model_name='policy',
            name='risk_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.risktype', verbose_name='Tipo de Riesgo (Dinámico)'),
        ),
    ]
