# Generated by Django 4.2.16 on 2026-05-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0021_risktype_alter_policy_tipo_poliza_policy_risk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='anulada',
            field=models.BooleanField(default=False, verbose_name='¿Póliza Anulada?'),
        ),
        migrations.AddField(
            model_name='policy',
            name='fecha_anulacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Anulación'),
        ),
        migrations.AddField(
            model_name='policy',
            name='motivo_anulacion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de la baja'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROXIMO', 'Próximo a vencer'), ('HOY', 'Vence hoy'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='fecha_primer_vencimiento_cuponera',
            field=models.DateField(blank=True, help_text='Si se deja vacío, se usará la fecha de inicio de la póliza.', null=True, verbose_name='Fecha primer vencimiento'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='frecuencia_cuponera',
            field=models.IntegerField(choices=[(1, 'Mensual'), (3, 'Trimestral'), (4, 'Cuatrimestral'), (6, 'Semestral'), (12, 'Anual')], default=1, verbose_name='Frecuencia de refacturación (meses)'),
        ),
    ]
