# Generated by Django 4.2.16 on 2026-05-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0022_policy_anulada_policy_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='patente',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Patente / Dominio'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['patente'], name='policies_po_patente_db21f5_idx'),
        ),
    ]
