# Generated by Django 4.2.16 on 2026-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0023_policy_patente_policy_policies_po_patente_db21f5_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="ultimo_envio_vencimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Último Aviso Vencimiento"
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="ultimo_envio_cuponera",
            field=models.DateField(
                blank=True, null=True, verbose_name="Última Cuponera Enviada"
            ),
        ),
    ]
