# Generated by Django 4.2.16 on 2026-05-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0023_policy_patente_policy_policies_po_patente_db21f5_idx"),
    ]

    operations = [
        # Se deja vacío porque las columnas ya fueron creadas manualmente
    ]
