# Generated by Django 4.2.16 on 2026-07-23 17:15

from django.db import migrations, models
import django.db.models.deletion
import policies.models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0024_auto_20260514_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='renovacion_de',
            field=models.ForeignKey(blank=True, help_text='Seleccione la póliza anterior correspondiente al mismo bien en caso de renovación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='policies.policy', verbose_name='Renueva a la póliza anterior'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to=policies.models.comprobante_directory_path, verbose_name='Archivo comprobante'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cuponera_pdf',
            field=models.FileField(blank=True, null=True, upload_to=policies.models.cuponera_directory_path, verbose_name='Archivo PDF cuponera'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='pdf_poliza',
            field=models.FileField(blank=True, null=True, upload_to=policies.models.policy_directory_path, verbose_name='Archivo PDF de póliza'),
        ),
    ]
