# Generated by Django 4.2.16 on 2026-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0025_policy_renovacion_de_alter_payment_comprobante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='anio_auto',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Año del Auto'),
        ),
        migrations.AddField(
            model_name='policy',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca del Auto'),
        ),
        migrations.AddField(
            model_name='policy',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo del Auto'),
        ),
        migrations.AddField(
            model_name='policy',
            name='version_auto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Versión del Auto'),
        ),
    ]
