# Generated by Django 4.2.16 on 2026-07-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0026_policy_anio_auto_policy_marca_policy_modelo_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='policy',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
                ),
            ],
            database_operations=[],  # No ejecuta nada en la base de datos porque la columna ya existe
        ),
    ]