# Generated by Django 4.2.16 on 2026-09-24 17:37

from django.db import migrations, models
import django.db.models.deletion
import policies.models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0027_policy_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Póliza',
                'verbose_name_plural': 'Tipos de Pólizas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='policy',
            name='email_15_dias_enviado',
            field=models.BooleanField(default=False, verbose_name='Email de aviso a 15 días enviado'),
        ),
        migrations.AddField(
            model_name='policy',
            name='fecha_fin_cobertura',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Fecha de Fin de Cobertura de Póliza'),
        ),
        migrations.AddField(
            model_name='policy',
            name='fecha_inicio_cobertura',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Cobertura de Póliza'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'Enviado'), ('ENVIADO_PRUEBA_ROJO', 'Enviado Prueba Modo Rojo'), ('ERROR', 'Error'), ('OMITIDO', 'Omitido')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='tipo',
            field=models.CharField(choices=[('AVISO_15_DIAS', 'Aviso de póliza a 15 días'), ('VENCIMIENTO_POLIZA', 'Vencimiento de póliza'), ('VENCIMIENTO_CUPONERA', 'Vencimiento de cuponera'), ('CUMPLEANOS', 'Cumpleaños')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comprobante',
            field=models.FileField(blank=True, max_length=500, null=True, storage=policies.models.SupabaseBypassStorage(), upload_to=policies.models.comprobante_directory_path, verbose_name='Archivo comprobante'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='cuponera_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, storage=policies.models.SupabaseBypassStorage(), upload_to=policies.models.cuponera_directory_path, verbose_name='Archivo PDF cuponera'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='pdf_poliza',
            field=models.FileField(blank=True, max_length=500, null=True, storage=policies.models.SupabaseBypassStorage(), upload_to=policies.models.policy_directory_path, verbose_name='Archivo PDF de póliza'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['fecha_fin_cobertura'], name='policies_po_fecha_f_6d5e0f_idx'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='tipo_poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='policies.policytype', verbose_name='Tipo de póliza (Categoría)'),
        ),
    ]
