# Generated by Django 4.2.16 on 2026-03-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_dni_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['last_name'], name='clients_cli_last_na_392efd_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['dni'], name='clients_cli_dni_fca805_idx'),
        ),
    ]
