# Generated by Django 4.2.16 on 2026-03-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_alter_client_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="permite_whatsapp",
            field=models.BooleanField(default=True, db_index=True),
        ),
        migrations.AddField(
            model_name="client",
            name="proximo_seguimiento",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="seguimiento_estado",
            field=models.CharField(
                choices=[
                    ("SIN_GESTION", "Sin gestión"),
                    ("PENDIENTE", "Pendiente"),
                    ("CONTACTADO", "Contactado"),
                    ("EN_SEGUIMIENTO", "En seguimiento"),
                    ("INTERESADO", "Interesado"),
                    ("NO_INTERESADO", "No interesado"),
                    ("CLIENTE", "Cliente"),
                ],
                db_index=True,
                default="SIN_GESTION",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="seguimiento_notas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="ultimo_contacto",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
