# Generated by Django 4.2.16 on 2026-03-28 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_permite_whatsapp_client_proximo_seguimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='permite_whatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
