# Generated by Django 4.2.16 on 2026-04-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_permite_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['fecha_nacimiento'], name='clients_cli_fecha_n_6b9abf_idx'),
        ),
    ]
