# Generated by Django 4.2.16 on 2026-09-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_force_password_change_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enviar_emails_a_clientes',
            field=models.BooleanField(default=True, verbose_name='Enviar emails a clientes'),
        ),
    ]
