# Generated by Django 4.2.16 on 2026-03-18 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('policies', '0011_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media')], db_index=True, max_length=10)),
                ('tipo', models.CharField(choices=[('DEUDA', 'Deuda'), ('VENCIMIENTO', 'Vencimiento'), ('MANUAL', 'Manual')], db_index=True, default='MANUAL', max_length=20)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
                'unique_together': {('policy', 'tipo', 'resolved')},
            },
        ),
    ]
