# Generated by Django 4.2.16 on 2026-03-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('resolved', False)), fields=('policy', 'tipo'), name='unique_active_alert_per_policy_tipo'),
        ),
    ]
