# Generated by Django 4.2.16 on 2026-03-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alerta', 'verbose_name_plural': 'Alertas'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
