# Generated by Django 4.2.16 on 2026-04-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0017_force_company_obj_column'),
        ('alerts', '0002_alter_alert_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.policy'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='tipo',
            field=models.CharField(choices=[('DEUDA', 'Deuda'), ('VENCIMIENTO', 'Vencimiento'), ('CUMPLEANIOS', 'Cumpleaños'), ('MANUAL', 'Manual')], db_index=True, default='MANUAL', max_length=20),
        ),
    ]
