- name: Ejecutar comando Django
  env:
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
    EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
    EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
    DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
    DEBUG: False
  run: |
    echo "📍 Carpeta actual:"
    pwd
    ls

    echo "📍 Comandos disponibles:"
    python manage.py help

    echo "📍 Buscando check_policies:"
    python manage.py help | grep check_policies || echo "NO EXISTE"

    python manage.py check_policies